// Shared domain types for the AKTU Autonomy system

export type Role =
  | "INSTITUTION_ADMIN"
  | "AUTHORIZED_SIGNATORY"
  | "DEALING_HAND"
  | "REGISTRAR_OFFICE"
  | "COMPETENT_AUTHORITY"
  | "COMMITTEE_MEMBER"
  | "ACCOUNTS_REVIEWER"
  | "LEGAL_REVIEWER"
  | "EXAMINATION_REVIEWER"
  | "AKTU_ADMIN";

export type ApplicationStatus =
  | "DRAFT"
  | "SUBMITTED_ONLINE_PENDING_HARDCOPY"
  | "HARDCOPY_RECEIVED_UNDER_SCRUTINY"
  | "DEFICIENCY_RAISED"
  | "SCRUTINY_CLEARED_READY_FOR_COMMITTEE_FORMATION"
  | "APPROVED_FOR_COMMITTEE_FORMATION"
  | "COMMITTEE_CONSTITUTED"
  | "MEETING_SCHEDULED"
  | "MOM_DRAFT_GENERATED"
  | "MOM_FINALIZED_SUBMITTED_TO_COMPETENT_AUTHORITY"
  | "DECISION_ISSUED_CLOSED";

export type UGCStatus =
  | "NOT_APPLIED"
  | "APPLIED"
  | "UNDER_PROCESS"
  | "CLARIFICATION_SOUGHT"
  | "APPROVED"
  | "APPROVED_WITH_CONDITIONS"
  | "REJECTED"
  | "WITHDRAWN";

